#!/usr/bin/env node
// Reads the wasm-pack output from uploader/pkg/ and generates
// src/web/wasm-assets.ts with the JS glue code and WASM binary embedded as
// strings. This makes the library fully self-contained — consumers need no
// bundler configuration to use the WASM uploader.
//
// Run automatically by: npm run build:rust:wasm
// Run manually with:    node uploader/scripts/embed-wasm.js

const fs = require('fs')
const path = require('path')

const pkgDir = path.join(__dirname, '../target/wasm')
const outFile = path.join(__dirname, '../../src/web/wasm-assets.ts')

const jsCode = fs.readFileSync(path.join(pkgDir, 'uploader.js'), 'utf-8')
const wasmBytes = fs.readFileSync(path.join(pkgDir, 'uploader_bg.wasm'))
const wasmBase64 = wasmBytes.toString('base64')

const content = `\
// Auto-generated by uploader/scripts/embed-wasm.js — do not edit manually.
// Regenerate by running: npm run build:rust:wasm

export const UPLOADER_JS_CODE = ${JSON.stringify(jsCode)}

export const UPLOADER_WASM_BASE64 = ${JSON.stringify(wasmBase64)}
`

fs.mkdirSync(path.dirname(outFile), { recursive: true })
fs.writeFileSync(outFile, content)
console.log('✓ WASM assets embedded →', path.relative(process.cwd(), outFile))
