[package]
name = "uploader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[features]
ios = ["nyquest"]
android = ["jni", "reqwest", "reqwest/blocking", "reqwest/rustls-tls-webpki-roots", "android_logger", "log", "libc"]
wasm = ["wasm-bindgen", "wasm-bindgen-file-reader", "web-sys", "wasm-bindgen-futures", "js-sys", "futures"]

[dependencies]
# https://github.com/rustwasm/wasm-bindgen
wasm-bindgen = { version = "0.2.88", optional = true }

# https://github.com/Badel2/wasm-bindgen-file-reader
wasm-bindgen-file-reader = { version = "1.0.0", optional = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# For parallel futures execution in WASM
futures = { version = "0.3", optional = true }

# For iOS native networking
nyquest = { version = "0.3", optional = true, features = ["blocking"] }
nyquest-backend-nsurlsession = { version = "0.3", features = ["blocking"] }

# For Android and WASM networking
reqwest = { version = "0.12", optional = true, default-features = false, features = ["json", "blocking"] }

# For Android JNI
jni = { version = "0.21", optional = true, default-features = false }
libc = { version = "0.2", optional = true }

# For Android logging
log = { version = "0.4", optional = true }
android_logger = { version = "0.14", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
js-sys = { version = "0.3", optional = true }

# Allows us to access browser elements like the console via Rust
# https://docs.rs/web-sys/latest/web_sys/
[dependencies.web-sys]
optional = true
version = "0.3.60"
# Log to the browser console from Rust code
features = [ 
    "console", 
    "Headers", 
    "Request", 
    "RequestInit", 
    "RequestMode", 
    "Response", 
    "Window", 
    "WorkerGlobalScope",
    "XmlHttpRequest",
    "XmlHttpRequestUpload",
    "ProgressEvent"
]

