// Auto-generated by uploader/scripts/embed-wasm.js — do not edit manually.
// Regenerate by running: npm run build:rust:wasm

export const UPLOADER_JS_CODE = ""
export const UPLOADER_WASM_BASE64 = ""